apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-funzone-deployment
  labels:
    app: k8s-funzone
spec:
  replicas: 3
  selector:
    matchLabels:
      app: k8s-funzone
  template:
    metadata:
      labels:
        app: k8s-funzone
      annotations:
        # See: https://www.elastic.co/guide/en/beats/filebeat/8.9/filebeat-input-container.html#filebeat-input-container-common-options
        co.elastic.logs/json.keys_under_root: 'true'
        co.elastic.logs/json.overwrite_keys: 'true'
        co.elastic.logs/json.add_error_key: 'true'
        co.elastic.logs/json.expand_keys: 'true'
    spec:
      imagePullSecrets:
        - name: regcred
      containers:
        - name: k8s-express-funzone
          image: gryphon2411/k8s-express-funzone:latest
          ports:
            - name: index
              containerPort: 3000
            - name: uselessfacts
              containerPort: 4000
        - name: k8s-fastapi-funzone
          image: gryphon2411/k8s-fastapi-funzone:latest
          ports:
            - containerPort: 5000