# The name of this workflow.
name: k8s express funzone ci

# Specifies that this workflow should run on every push event for the branches in the list.
on:
  push:
    branches:
      - master
    paths:
      - k8s-express-funzone/**

# Creates a job ID (build) and declares the type of machine that the job should run on.
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checks out the repository on the build machine.
      - name: Checkout
        uses: actions/checkout@v3.5.3
      
      # Signs in to Docker Hub, using the "Docker Login" action and your Docker Hub credentials.
      - name: Login to Docker Hub
        uses: docker/login-action@v2.2.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      # Creates a BuildKit builder instance using the "Docker Setup Buildx" action.
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        
      # Builds the container image and pushes it to the Docker Hub repository, using "Build and push Docker images".
      - name: Build and push
        uses: docker/build-push-action@v4.1.1
        with:
          # The build context (https://docs.docker.com/build/building/context/), default is "."
          context: k8s-express-funzone/
          # Filepath to the Dockerfile, default is "./Dockerfile"
          file: k8s-express-funzone/Dockerfile
          # Tells the action to upload the image to a registry after building it.
          push: true
          # Tags that specify where to push the image.
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/k8s-express-funzone:latest
